# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import formapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('formapi', '0004_auto_20160227_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckboxElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('label', models.CharField(default=b'label', max_length=255)),
                ('form', models.ForeignKey(default=formapi.models.Form(1, 'test'), on_delete=django.db.models.deletion.CASCADE, to='formapi.Form')),
            ],
        ),
        migrations.CreateModel(
            name='CheckboxItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('label', models.CharField(default=b'label', max_length=255)),
                ('choiceelement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapi.CheckboxElement')),
            ],
        ),
        migrations.CreateModel(
            name='DropdownElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('label', models.CharField(default=b'label', max_length=255)),
                ('form', models.ForeignKey(default=formapi.models.Form(1, 'test'), on_delete=django.db.models.deletion.CASCADE, to='formapi.Form')),
            ],
        ),
        migrations.CreateModel(
            name='DropdownItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('label', models.CharField(default=b'label', max_length=255)),
                ('value', models.CharField(default=b'label', max_length=255)),
                ('selected', models.BooleanField(default=False)),
                ('dropdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapi.DropdownElement')),
            ],
        ),
        migrations.CreateModel(
            name='InputElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('label', models.CharField(default=b'label', max_length=255)),
                ('placeholder', models.CharField(blank=True, default=b'placeholder', max_length=255)),
                ('hidden', models.BooleanField(default=False)),
                ('form', models.ForeignKey(default=formapi.models.Form(1, 'test'), on_delete=django.db.models.deletion.CASCADE, to='formapi.Form')),
            ],
        ),
        migrations.CreateModel(
            name='RadioElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('label', models.CharField(default=b'label', max_length=255)),
                ('form', models.ForeignKey(default=formapi.models.Form(1, 'test'), on_delete=django.db.models.deletion.CASCADE, to='formapi.Form')),
            ],
        ),
        migrations.CreateModel(
            name='RadioItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('label', models.CharField(default=b'label', max_length=255)),
                ('selected', models.BooleanField(default=False)),
                ('radioelement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapi.RadioElement')),
            ],
        ),
        migrations.CreateModel(
            name='TextItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('text', models.TextField()),
                ('form', models.ForeignKey(default=formapi.models.Form(1, 'test'), on_delete=django.db.models.deletion.CASCADE, to='formapi.Form')),
            ],
        ),
        migrations.RemoveField(
            model_name='formelement',
            name='form',
        ),
        migrations.DeleteModel(
            name='FormElement',
        ),
    ]
