# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapi', '0005_auto_20160308_2235'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TextItem',
            new_name='TextElement',
        ),
        migrations.RemoveField(
            model_name='checkboxitem',
            name='choiceelement',
        ),
        migrations.DeleteModel(
            name='CheckboxItem',
        ),
    ]
