# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapi', '0007_auto_20160312_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radioitem',
            old_name='label',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='radioitem',
            name='selected',
        ),
    ]
