# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapi', '0008_auto_20160312_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='RangeElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
