# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapi', '0015_rangeelement_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='textelement',
            name='label',
            field=models.CharField(default=b'label', max_length=255),
        ),
    ]
