# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapi', '0017_auto_20160312_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkboxelement',
            name='show_on_listview',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dropdownelement',
            name='show_on_listview',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inputelement',
            name='show_on_listview',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='radioelement',
            name='show_on_listview',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rangeelement',
            name='show_on_listview',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='textelement',
            name='show_on_listview',
            field=models.BooleanField(default=True),
        ),
    ]
